# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in mod_file.gemspec
gemspec

gem "rake", "~> 13.0"

gem "faker"

gem "rspec"

gem "minitest", "~> 5.0"

gem "rubocop", "~> 1.21"
